package org.lvelez.book;

public enum BookGenre {
    ACTION, ADVENTURE, ANTHOLOGY, CLASSIC, COMIC, CRIME, DRAMA, FABLE, FAIRYTALE, FANFIC, FANTASY, HISTORICAL,
    HORROR, HUMOR, MISTERY, MYTHOLOGY, ROMANCE, SATIRE, SCIFI, THRILLER, BIOGRAPHY, ESSAY, SELFHELP, TEXTBOOK,
    POETRY
}
